import { Ionicons } from '@expo/vector-icons';
import { useEffect, useRef, useState } from 'react';
import { ActivityIndicator, Alert, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Colors, Radius } from '../src/constants/theme';
import { api } from '../src/services/api';
import { StaffBooking } from '../src/types/staff';

// A PENDING request whose date is already over can't be worked any more; don't offer Accept.
const isPast=(date:string)=>{const d=new Date(date);d.setHours(23,59,59,999);return d.getTime()<Date.now();};

// Declined/cancelled requests shared the green 'confirmed' badge.
const CLOSED=['CANCELLED','REJECTED'];
export default function Bookings(){
  const [items,setItems]=useState<StaffBooking[]>([]); const [loading,setLoading]=useState(true); const [acting,setActing]=useState<string>();
  const [failed,setFailed]=useState(false);
  // Errors used to be unhandled rejections that rendered as "No work requests".
  const load=async()=>{try{const r=await api.get('/staff-app/bookings');setItems(r.data.data??[]);setFailed(false);}catch{setFailed(true);}finally{setLoading(false);}};
  useEffect(()=>{load();},[]);
  // Pull-to-refresh needs its own flag: onRefresh={load} never set `loading`, so the spinner vanished on release.
  const [refreshing,setRefreshing]=useState(false);
  const refresh=async()=>{setRefreshing(true);try{await load();}finally{setRefreshing(false);}};
  const busy=useRef(false);
  // Ref guard: a fast double tap fires twice before `acting` re-renders the buttons disabled.
  const act=async(item:StaffBooking, action:'accept'|'reject')=>{if(busy.current)return;busy.current=true;setActing(item.id);try{await api.patch(`/staff-app/bookings/${item.id}/${action}`,action==='reject'?{rejectionReason:'Not available at this time'}:undefined);await load();}catch(e:any){Alert.alert('Could not update request',e.response?.data?.message||'Please try again.');load();}finally{busy.current=false;setActing(undefined);}};
  return <ScrollView style={s.root} contentContainerStyle={s.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={refresh} tintColor={Colors.gold} colors={[Colors.gold]}/>}>
    {loading?<ActivityIndicator style={s.loader} color={Colors.gold}/>:items.length?items.map(item=><View style={s.card} key={item.id}><View style={s.top}><View style={s.workIcon}><Ionicons name="briefcase-outline" size={22} color={Colors.ink}/></View><View style={s.info}><Text style={s.work}>{item.workType}</Text><Text style={s.home}>{item.flat.block?.name ? `${item.flat.block.name} · ` : ''}{item.flat.flatNumber}</Text></View><View style={[s.badge,item.status==='PENDING'&&s.pending,CLOSED.includes(item.status)&&s.closed]}><Text style={[s.badgeText,CLOSED.includes(item.status)&&s.closedText]}>{item.status}</Text></View></View><View style={s.meta}><Text style={s.metaText}>{new Date(item.bookingDate).toLocaleDateString('en-IN',{day:'numeric',month:'short'})}</Text><Text style={s.dot}>•</Text><Text style={s.metaText}>{item.startTime} – {item.endTime}</Text></View>{item.requirements?<Text style={s.requirements}>{item.requirements}</Text>:null}{item.status==='PENDING'&&isPast(item.bookingDate)?<Text style={s.expired}>This request date has passed.</Text>:item.status==='PENDING'?<View style={s.actions}><Pressable disabled={!!acting} style={s.reject} onPress={()=>Alert.alert('Decline this request?','The resident will be told you are not available.',[{text:'Keep',style:'cancel'},{text:'Decline',style:'destructive',onPress:()=>act(item,'reject')}])}><Text style={s.rejectText}>Decline</Text></Pressable><Pressable disabled={!!acting} style={s.accept} onPress={()=>act(item,'accept')}>{acting===item.id?<ActivityIndicator color={Colors.ink}/>:<Text style={s.acceptText}>Accept work</Text>}</Pressable></View>:null}</View>):<View style={s.empty}><View style={s.icon}><Ionicons name="briefcase-outline" size={35} color={Colors.soft}/></View><Text style={s.title}>{failed?'Could not load requests':'No work requests'}</Text><Text style={s.text}>{failed?'Check your connection and pull down to try again.':'New resident work requests will appear here for you to review.'}</Text></View>}
  </ScrollView>;
}
const s=StyleSheet.create({root:{flex:1,backgroundColor:Colors.bg},content:{padding:20,flexGrow:1},loader:{marginTop:60},card:{backgroundColor:Colors.card,borderWidth:1,borderColor:Colors.border,borderRadius:Radius.lg,padding:17,marginBottom:12},top:{flexDirection:'row',alignItems:'center'},workIcon:{width:45,height:45,borderRadius:15,backgroundColor:Colors.goldPale,alignItems:'center',justifyContent:'center'},info:{flex:1,marginLeft:12},work:{fontSize:16,fontWeight:'900',color:Colors.ink},home:{fontSize:12,color:Colors.muted,marginTop:3},badge:{paddingHorizontal:8,paddingVertical:5,borderRadius:9,backgroundColor:Colors.greenPale},pending:{backgroundColor:Colors.goldPale},closed:{backgroundColor:Colors.redPale},closedText:{color:Colors.red},badgeText:{fontSize:9,fontWeight:'900',color:Colors.ink},meta:{flexDirection:'row',marginTop:15,alignItems:'center'},metaText:{fontSize:12,fontWeight:'700',color:Colors.muted},dot:{marginHorizontal:8,color:Colors.soft},requirements:{fontSize:13,lineHeight:19,color:Colors.ink,backgroundColor:Colors.bg,padding:12,borderRadius:12,marginTop:12},actions:{flexDirection:'row',gap:9,marginTop:16},reject:{flex:1,minHeight:46,borderRadius:14,borderWidth:1,borderColor:Colors.border,alignItems:'center',justifyContent:'center'},rejectText:{fontWeight:'900',color:Colors.muted},accept:{flex:1.5,minHeight:46,borderRadius:14,backgroundColor:Colors.gold,alignItems:'center',justifyContent:'center'},acceptText:{fontWeight:'900',color:Colors.ink},expired:{fontSize:12,fontWeight:'700',color:Colors.soft,marginTop:14},empty:{flex:1,alignItems:'center',justifyContent:'center',padding:38},icon:{width:74,height:74,borderRadius:24,backgroundColor:Colors.greenPale,alignItems:'center',justifyContent:'center'},title:{fontSize:20,fontWeight:'900',color:Colors.ink,marginTop:18},text:{fontSize:13,lineHeight:20,textAlign:'center',color:Colors.muted,marginTop:7}});
