import { Ionicons } from '@expo/vector-icons';
import { useEffect, useState } from 'react';
import { ActivityIndicator, Alert, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Colors, Radius } from '../src/constants/theme';
import { api } from '../src/services/api';
import { StaffBooking } from '../src/types/staff';

export default function Bookings(){
  const [items,setItems]=useState<StaffBooking[]>([]); const [loading,setLoading]=useState(true); const [acting,setActing]=useState<string>();
  const load=async()=>{try{const r=await api.get('/staff-app/bookings');setItems(r.data.data);}finally{setLoading(false);}};
  useEffect(()=>{load();},[]);
  const act=async(item:StaffBooking, action:'accept'|'reject')=>{setActing(item.id);try{await api.patch(`/staff-app/bookings/${item.id}/${action}`,action==='reject'?{rejectionReason:'Not available at this time'}:undefined);await load();}catch(e:any){Alert.alert('Could not update request',e.response?.data?.message||'Please try again.');}finally{setActing(undefined);}};
  return <ScrollView style={s.root} contentContainerStyle={s.content} refreshControl={<RefreshControl refreshing={loading} onRefresh={load} tintColor={Colors.gold}/>}>
    {loading?<ActivityIndicator style={s.loader} color={Colors.gold}/>:items.length?items.map(item=><View style={s.card} key={item.id}><View style={s.top}><View style={s.workIcon}><Ionicons name="briefcase-outline" size={22} color={Colors.ink}/></View><View style={s.info}><Text style={s.work}>{item.workType}</Text><Text style={s.home}>{item.flat.block?.name} · {item.flat.flatNumber}</Text></View><View style={[s.badge,item.status==='PENDING'&&s.pending]}><Text style={s.badgeText}>{item.status}</Text></View></View><View style={s.meta}><Text style={s.metaText}>{new Date(item.bookingDate).toLocaleDateString('en-IN',{day:'numeric',month:'short'})}</Text><Text style={s.dot}>•</Text><Text style={s.metaText}>{item.startTime} – {item.endTime}</Text></View>{item.requirements?<Text style={s.requirements}>{item.requirements}</Text>:null}{item.status==='PENDING'?<View style={s.actions}><Pressable disabled={!!acting} style={s.reject} onPress={()=>act(item,'reject')}><Text style={s.rejectText}>Decline</Text></Pressable><Pressable disabled={!!acting} style={s.accept} onPress={()=>act(item,'accept')}>{acting===item.id?<ActivityIndicator color={Colors.ink}/>:<Text style={s.acceptText}>Accept work</Text>}</Pressable></View>:null}</View>):<View style={s.empty}><View style={s.icon}><Ionicons name="briefcase-outline" size={35} color={Colors.soft}/></View><Text style={s.title}>No work requests</Text><Text style={s.text}>New resident work requests will appear here for you to review.</Text></View>}
  </ScrollView>;
}
const s=StyleSheet.create({root:{flex:1,backgroundColor:Colors.bg},content:{padding:20,flexGrow:1},loader:{marginTop:60},card:{backgroundColor:Colors.card,borderWidth:1,borderColor:Colors.border,borderRadius:Radius.lg,padding:17,marginBottom:12},top:{flexDirection:'row',alignItems:'center'},workIcon:{width:45,height:45,borderRadius:15,backgroundColor:Colors.goldPale,alignItems:'center',justifyContent:'center'},info:{flex:1,marginLeft:12},work:{fontSize:16,fontWeight:'900',color:Colors.ink},home:{fontSize:12,color:Colors.muted,marginTop:3},badge:{paddingHorizontal:8,paddingVertical:5,borderRadius:9,backgroundColor:Colors.greenPale},pending:{backgroundColor:Colors.goldPale},badgeText:{fontSize:9,fontWeight:'900',color:Colors.ink},meta:{flexDirection:'row',marginTop:15,alignItems:'center'},metaText:{fontSize:12,fontWeight:'700',color:Colors.muted},dot:{marginHorizontal:8,color:Colors.soft},requirements:{fontSize:13,lineHeight:19,color:Colors.ink,backgroundColor:Colors.bg,padding:12,borderRadius:12,marginTop:12},actions:{flexDirection:'row',gap:9,marginTop:16},reject:{flex:1,minHeight:46,borderRadius:14,borderWidth:1,borderColor:Colors.border,alignItems:'center',justifyContent:'center'},rejectText:{fontWeight:'900',color:Colors.muted},accept:{flex:1.5,minHeight:46,borderRadius:14,backgroundColor:Colors.gold,alignItems:'center',justifyContent:'center'},acceptText:{fontWeight:'900',color:Colors.ink},empty:{flex:1,alignItems:'center',justifyContent:'center',padding:38},icon:{width:74,height:74,borderRadius:24,backgroundColor:Colors.greenPale,alignItems:'center',justifyContent:'center'},title:{fontSize:20,fontWeight:'900',color:Colors.ink,marginTop:18},text:{fontSize:13,lineHeight:20,textAlign:'center',color:Colors.muted,marginTop:7}});
