import { Ionicons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Colors, Radius } from '../src/constants/theme';
import { useAuth } from '../src/store/auth';

const actions = [
  { label: 'Gate pass', detail: 'Show QR at gate', icon: 'qr-code-outline' as const, route: '/pass' as const, tint: Colors.goldPale },
  { label: 'My schedule', detail: 'Homes and timings', icon: 'calendar-outline' as const, route: '/schedule' as const, tint: Colors.bluePale },
  { label: 'Work requests', detail: 'Accept new work', icon: 'briefcase-outline' as const, route: '/bookings' as const, tint: Colors.greenPale },
  { label: 'My profile', detail: 'Details and support', icon: 'person-outline' as const, route: '/profile' as const, tint: '#F1EEFF' },
];

export default function Home() {
  const insets = useSafeAreaInsets(); const router = useRouter(); const staff = useAuth((s) => s.staff);
  return <View style={s.root}><ScrollView contentContainerStyle={[s.content,{paddingTop:insets.top+20,paddingBottom:insets.bottom+30}]} showsVerticalScrollIndicator={false}><View style={s.top}><View><Text style={s.brand}>S-GATE</Text><Text style={s.brandSub}>STAFF</Text></View><Pressable style={s.avatar} onPress={()=>router.push('/profile')}><Text style={s.avatarText}>{staff?.name?.[0] ?? 'S'}</Text></Pressable></View><Text style={s.eyebrow}>GOOD MORNING</Text><Text style={s.hello}>Ready for work,{`\n`}{staff?.name?.split(' ')[0] ?? 'friend'}?</Text><View style={s.verify}><Ionicons name="shield-checkmark" size={17} color={Colors.green}/><Text style={s.verifyText}>{staff?.isVerified === false ? 'Verification pending' : 'Society verified'}</Text></View><View style={s.statusCard}><View><Text style={s.statusLabel}>TODAY’S STATUS</Text><Text style={s.statusTitle}>{staff?.isCurrentlyWorking ? 'Currently working' : 'Outside society'}</Text><Text style={s.statusText}>{staff?.isCurrentlyWorking ? 'Your active work session is being recorded.' : 'Show your gate pass when you arrive.'}</Text></View><View style={[s.statusIcon,{backgroundColor:staff?.isCurrentlyWorking?Colors.greenPale:Colors.goldPale}]}><Ionicons name={staff?.isCurrentlyWorking?'time':'walk'} size={28} color={staff?.isCurrentlyWorking?Colors.green:'#D39200'}/></View></View><View style={s.sectionRow}><Text style={s.section}>QUICK ACCESS</Text><Text style={s.sectionHint}>Everything you need</Text></View><View style={s.grid}>{actions.map((a)=><Pressable key={a.label} style={s.card} onPress={()=>router.push(a.route)}><View style={[s.actionIcon,{backgroundColor:a.tint}]}><Ionicons name={a.icon} size={25} color={Colors.ink}/></View><Text style={s.actionLabel}>{a.label}</Text><Text style={s.actionDetail}>{a.detail}</Text></Pressable>)}</View><View style={s.next}><View style={s.nextTop}><Text style={s.nextKicker}>NEXT WORK</Text><View style={s.timeBadge}><Text style={s.timeText}>8:00 AM</Text></View></View><Text style={s.nextTitle}>No work scheduled yet</Text><Text style={s.nextText}>Your assigned homes and accepted bookings will appear here.</Text><Pressable style={s.scheduleLink} onPress={()=>router.push('/schedule')}><Text style={s.scheduleLinkText}>View full schedule</Text><Ionicons name="arrow-forward" size={16} color={Colors.ink}/></Pressable></View></ScrollView></View>;
}
const s=StyleSheet.create({root:{flex:1,backgroundColor:Colors.bg},content:{paddingHorizontal:20},top:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},brand:{fontSize:25,fontWeight:'900',color:Colors.ink},brandSub:{fontSize:10,fontWeight:'900',letterSpacing:3,color:Colors.soft},avatar:{width:52,height:52,borderRadius:18,backgroundColor:Colors.ink,alignItems:'center',justifyContent:'center'},avatarText:{fontSize:20,fontWeight:'900',color:Colors.gold},eyebrow:{marginTop:42,fontSize:12,fontWeight:'900',letterSpacing:2,color:'#D39200'},hello:{fontSize:38,lineHeight:43,fontWeight:'900',color:Colors.ink,marginTop:8},verify:{alignSelf:'flex-start',flexDirection:'row',alignItems:'center',gap:6,backgroundColor:Colors.greenPale,paddingHorizontal:11,paddingVertical:7,borderRadius:14,marginTop:14},verifyText:{fontSize:12,fontWeight:'800',color:'#078463'},statusCard:{marginTop:25,backgroundColor:Colors.ink,borderRadius:Radius.lg,padding:20,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},statusLabel:{fontSize:10,fontWeight:'900',letterSpacing:1.5,color:'#AEB3BF'},statusTitle:{fontSize:21,fontWeight:'900',color:'#FFF',marginTop:8},statusText:{fontSize:12,lineHeight:18,color:'#BFC3CD',marginTop:4,maxWidth:240},statusIcon:{width:54,height:54,borderRadius:18,alignItems:'center',justifyContent:'center'},sectionRow:{flexDirection:'row',alignItems:'flex-end',justifyContent:'space-between',marginTop:29,marginBottom:12},section:{fontSize:12,fontWeight:'900',letterSpacing:1.8,color:Colors.soft},sectionHint:{fontSize:11,color:Colors.soft},grid:{flexDirection:'row',flexWrap:'wrap',gap:10},card:{width:'48.5%',minHeight:145,backgroundColor:Colors.card,borderRadius:Radius.md,borderWidth:1,borderColor:Colors.border,padding:15},actionIcon:{width:46,height:46,borderRadius:15,alignItems:'center',justifyContent:'center'},actionLabel:{fontSize:15,fontWeight:'900',color:Colors.ink,marginTop:18},actionDetail:{fontSize:11,color:Colors.soft,marginTop:4},next:{marginTop:22,backgroundColor:Colors.goldPale,borderWidth:1,borderColor:'#F0D77B',borderRadius:Radius.lg,padding:19},nextTop:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},nextKicker:{fontSize:10,fontWeight:'900',letterSpacing:1.5,color:'#A66E00'},timeBadge:{backgroundColor:Colors.gold,paddingHorizontal:10,paddingVertical:6,borderRadius:10},timeText:{fontSize:11,fontWeight:'900',color:Colors.ink},nextTitle:{fontSize:18,fontWeight:'900',color:Colors.ink,marginTop:16},nextText:{fontSize:12,lineHeight:18,color:Colors.muted,marginTop:5},scheduleLink:{flexDirection:'row',alignItems:'center',gap:7,marginTop:17},scheduleLinkText:{fontSize:13,fontWeight:'900',color:Colors.ink}});
