import { Ionicons } from '@expo/vector-icons';
import { useEffect, useState } from 'react';
import { ActivityIndicator, StyleSheet, Text, View } from 'react-native';
import QRCode from 'react-native-qrcode-svg';
import { Colors, Radius } from '../src/constants/theme';
import { api } from '../src/services/api';
import { useAuth } from '../src/store/auth';
export default function Pass(){const staff=useAuth(s=>s.staff);const[token,setToken]=useState('');useEffect(()=>{api.get('/staff-app/pass').then(r=>setToken(r.data.data.qrToken)).catch(()=>undefined)},[]);return <View style={s.root}><View style={s.card}><View style={s.shield}><Ionicons name="shield-checkmark" size={25} color={Colors.ink}/></View><Text style={s.brand}>S-GATE STAFF PASS</Text><View style={s.qr}>{token?<QRCode value={token} size={190} color={Colors.ink} backgroundColor="#FFFFFF"/>:<ActivityIndicator color={Colors.gold}/>}</View><Text style={s.name}>{staff?.name??'Staff member'}</Text><Text style={s.type}>{staff?.staffType?.replace(/_/g,' ')??'DOMESTIC STAFF'}</Text><View style={s.verified}><Ionicons name="checkmark-circle" size={17} color={Colors.green}/><Text style={s.verifiedText}>VERIFIED PASS</Text></View></View><Text style={s.help}>Show this pass to security when entering or leaving the society.</Text></View>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:Colors.bg,padding:22,justifyContent:'center'},card:{backgroundColor:Colors.card,borderRadius:Radius.xl,borderWidth:1,borderColor:Colors.border,padding:26,alignItems:'center'},shield:{width:54,height:54,borderRadius:18,backgroundColor:Colors.gold,alignItems:'center',justifyContent:'center'},brand:{fontSize:12,fontWeight:'900',letterSpacing:2,color:Colors.muted,marginTop:14},qr:{padding:18,borderRadius:24,backgroundColor:'#FFF',borderWidth:1,borderColor:Colors.border,marginTop:24},name:{fontSize:25,fontWeight:'900',color:Colors.ink,marginTop:22},type:{fontSize:12,fontWeight:'800',letterSpacing:1.5,color:Colors.soft,marginTop:5},verified:{flexDirection:'row',gap:6,alignItems:'center',backgroundColor:Colors.greenPale,paddingHorizontal:12,paddingVertical:8,borderRadius:14,marginTop:17},verifiedText:{fontSize:11,fontWeight:'900',color:'#078463'},help:{fontSize:13,lineHeight:19,textAlign:'center',color:Colors.muted,marginTop:20,paddingHorizontal:22}});
